services: 
    web:
        image: tomcat:10
        ports: 
            - 8080:8080
        depends_on:
          db:
            condition: service_healthy
        volumes:
            - ./crane.war:/usr/local/tomcat/webapps/crane.war
    db:
        image: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        volumes:
            - ./crane.sql:/docker-entrypoint-initdb.d/init.sql
            - ./data/db:/var/lib/postgresql/data

        healthcheck:
            test: ["CMD-SHELL", "pg_isready", "-U psostgres"]
            interval: 5s
            timeout: 10s
            retries: 50